version: "3.8"

services:

  app:
    container_name: frotapm-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/frotapm
      SPRING_DATASOURCE_USERNAME: frotapm
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frotapm.rule=Host(`api.pmto8bpm.com.br`)"
      - "traefik.http.routers.frotapm.entrypoints=websecure"
      - "traefik.http.routers.frotapm.tls=true"
      - "traefik.http.routers.frotapm.tls.certresolver=letsencrypt"
      - "traefik.http.services.frotapm.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.frotapm-cors.headers.accessControlAllowOriginList=https://localhost:5173"
      - "traefik.http.middlewares.frotapm-cors.headers.accessControlAllowMethods=GET,POST,OPTIONS,PUT,DELETE"
      - "traefik.http.middlewares.frotapm-cors.headers.accessControlAllowHeaders=Authorization,Content-Type,X-Client-Type"
      - "traefik.http.middlewares.frotapm-cors.headers.accessControlAllowCredentials=true"

  db:
    container_name: frotapm-postgres
    image: postgres:15
    restart: always
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: frotapm
      POSTGRES_USER: frotapm
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
